name: EconomyUtilsAPI
version: '${project.version}'
main: com.tatamiserver.economyutilsapi.EconomyUtilsAPI
api-version: 1.13
depend: [ QuickShop, VaultAPI ]
softdepend: [ QuickShop, VaultAPI ]
authors: [ kuripasanda ]
